name: imlabtools
channels:
  - conda-forge
  - defaults
  - moble
  - bioconda
dependencies:
  - python=3.7
  - pandas=1.3.5
  - scipy=1.7.3
  - numpy=1.21.2
  - bgen-reader=4.0.8
  - cyvcf2=0.30.14
  - pyliftover=0.4
  - statsmodels=0.13.0
  - h5py=3.6.0
  - pyarrow=4.0.1

